<?php

/**
 * Soap client GeoIpService
 *
 * Autogenerated with the Yii extension wsdl2php.
 */
class GetGeoIP {

    public $IPAddress; //string;

}

class GetGeoIPResponse {

    public $GetGeoIPResult; //GeoIP;

}

class GeoIP {

    public $ReturnCode; //int;
    public $IP; //string;
    public $ReturnCodeDetails; //string;
    public $CountryName; //string;
    public $CountryCode; //string;

}

class GetGeoIPContext {

}

class GetGeoIPContextResponse {

    public $GetGeoIPContextResult; //GeoIP;

}

/**
 * The soap client proxy class
 */
class GeoIpService {

    public $soapClient;
    private static $classmap = array(
        'GetGeoIP' => 'GetGeoIP',
        'GetGeoIPResponse' => 'GetGeoIPResponse',
        'GeoIP' => 'GeoIP',
        'GetGeoIPContext' => 'GetGeoIPContext',
        'GetGeoIPContextResponse' => 'GetGeoIPContextResponse',
    );

    function __construct($url = 'http://www.webservicex.net/geoipservice.asmx?WSDL') {
        $this->soapClient = new SoapClient($url, array("classmap" => self::$classmap, "trace" => true, "exceptions" => true));
    }

    function GetGeoIP($GetGeoIP) {
        $GetGeoIPResponse = $this->soapClient->GetGeoIP($GetGeoIP);
        return $GetGeoIPResponse;
    }

    function GetGeoIPContext($GetGeoIPContext) {
        $GetGeoIPContextResponse = $this->soapClient->GetGeoIPContext($GetGeoIPContext);
        return $GetGeoIPContextResponse;
    }

}

