<?php

/**
 * This is the model base class for the table "GearboxTransmission".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GearboxTransmission".
 *
 * Columns in table "GearboxTransmission" available as properties of the model,
 * followed by relations of table "GearboxTransmission" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Automobile[] $automobiles
 */
abstract class BaseGearboxTransmission extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'GearboxTransmission';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Gearbox Transmission|Gearbox Transmissions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'automobiles' => array(self::HAS_MANY, 'Automobile', 'GearboxTransmission_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                        			                        'automobiles' => yii::t('app', 'Automobiles'),
		);
	}

    public function defaultScope() {
        return array('order' => BaseGearboxTransmission::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}