<?php

/**
 * This is the model base class for the table "Cfd_has_Annotation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdHasAnnotation".
 *
 * Columns in table "Cfd_has_Annotation" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Cfd_id
 * @property integer $Annotation_id
 *
 */
abstract class BaseCfdHasAnnotation extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Cfd_has_Annotation';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Has Annotation|Cfd Has Annotations', $n);
	}

	public static function representingColumn() {
		return array(
			'Cfd_id',
			'Annotation_id',
		);
	}

	public function relations() {
		$relations = array(
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Cfd_id, Annotation_id', 'required'),
			array('Cfd_id, Annotation_id', 'numerical', 'integerOnly'=>true),
			array('Cfd_id, Annotation_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Cfd_id', $this->Cfd_id);
		$criteria->compare('Annotation_id', $this->Annotation_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                        			                        'Cfd_id' => yii::t('app', 'Cfd'),
                        			                        'Annotation_id' => yii::t('app', 'Annotation'),
		);
	}
}