<?php

/**
 * This is the model base class for the table "PartyRole".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyRole".
 *
 * Columns in table "PartyRole" available as properties of the model,
 * followed by relations of table "PartyRole" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $active
 *
 * @property PartyHasRole[] $partyHasRoles
 */
abstract class BasePartyRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyRole';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Role|Party Roles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('code', 'length', 'max'=>45),
			array('name, code, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, code, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'partyHasRoles' => array(self::HAS_MANY, 'PartyHasRole', 'PartyRole_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'code' => yii::t('app', 'Code'),
                			'active' => yii::t('app', 'Active'),
                        			                        'partyHasRoles' => yii::t('app', 'Party Has Roles'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BasePartyRole::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}