<?php

/**
 * This is the model base class for the table "State".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "State".
 *
 * Columns in table "State" available as properties of the model,
 * followed by relations of table "State" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $Country_id
 *
 * @property Address[] $addresses
 * @property RegisterForm[] $registerForms
 * @property Country $country
 */
abstract class BaseState extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'State';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'State|States', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, code, Country_id', 'required'),
			array('Country_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>45),
			array('id, name, code, Country_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'addresses' => array(self::HAS_MANY, 'Address', 'State_id'),
			'registerForms' => array(self::HAS_MANY, 'RegisterForm', 'State_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'Country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'code' => yii::t('app', 'Code'),
                        			                        'Country_id' => yii::t('app', 'Country'),
                        			                        'addresses' => yii::t('app', 'Addresses'),
                        			                        'registerForms' => yii::t('app', 'Register Forms'),
                        			                        'country' => yii::t('app', 'Country'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('Country_id', $this->Country_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}