<?php

/**
 * This is the model base class for the table "PartyType".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyType".
 *
 * Columns in table "PartyType" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 * @property integer $personType
 * @property integer $businessType
 *
 */
abstract class BasePartyType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyType';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Type|Party Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('active, personType, businessType', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('name, active, personType, businessType', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, active, personType, businessType', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'active' => yii::t('app', 'Active'),
                			'personType' => yii::t('app', 'Person Type'),
                			'businessType' => yii::t('app', 'Business Type'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BasePartyType::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('personType', $this->personType);
		$criteria->compare('businessType', $this->businessType);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}