<?php

/**
 * This is the model base class for the table "PartyRole".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyRole".
 *
 * Columns in table "PartyRole" available as properties of the model,
 * followed by relations of table "PartyRole" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property integer $Role_id
 * @property integer $enabled
 * @property string $effDt
 *
 * @property PartyRelationship[] $partyRelationships
 * @property PartyRelationship[] $partyRelationships1
 * @property Party $party
 * @property Role $role
 */
abstract class BasePartyRole extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyRole';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Role|Party Roles', $n);
	}

	public static function representingColumn() {
		return 'effDt';
	}

	public function relations() {
		$relations = array(
			'partyRelationships' => array(self::HAS_MANY, 'PartyRelationship', 'fromPartyRole_id'),
			'partyRelationships1' => array(self::HAS_MANY, 'PartyRelationship', 'toPartyRole_id'),
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'role' => array(self::BELONGS_TO, 'Role', 'Role_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Party_id, Role_id', 'required'),
			array('Party_id, Role_id, enabled', 'numerical', 'integerOnly'=>true),
			array('effDt', 'safe'),
			array('enabled, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, Role_id, enabled, effDt', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('Role_id', $this->Role_id);
		$criteria->compare('enabled', $this->enabled);
		$criteria->compare('effDt', $this->effDt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'Role_id' => yii::t('app', 'Role'),
                			'enabled' => yii::t('app', 'Enabled'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'partyRelationships' => yii::t('app', 'Party Relationships'),
                        			                        'partyRelationships1' => yii::t('app', 'Party Relationships1'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'role' => yii::t('app', 'Role'),
		);
	}
}