<?php

/**
 * This is the model base class for the table "PartyIdentifier".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyIdentifier".
 *
 * Columns in table "PartyIdentifier" available as properties of the model,
 * followed by relations of table "PartyIdentifier" available as properties of the model.
 *
 * @property integer $id
 * @property string $value
 * @property string $type
 * @property string $effDt
 * @property integer $Party_id
 *
 * @property Party $party
 */
abstract class BasePartyIdentifier extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyIdentifier';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Identifier|Party Identifiers', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function relations() {
		$relations = array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Party_id', 'required'),
			array('Party_id', 'numerical', 'integerOnly'=>true),
			array('value, type', 'length', 'max'=>45),
			array('effDt', 'safe'),
			array('value, type, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, value, type, effDt, Party_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('effDt', $this->effDt, true);
		$criteria->compare('Party_id', $this->Party_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
                        'sort' => array(
                            'defaultOrder' => array(
                                $this->representingColumn() => CSort::SORT_ASC
                            )
                        )
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'value' => yii::t('app', 'Value'),
                			'type' => yii::t('app', 'Type'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}
}