<?php

/**
 * This is the model base class for the table "PartyLocator".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyLocator".
 *
 * Columns in table "PartyLocator" available as properties of the model,
 * followed by relations of table "PartyLocator" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property string $class
 * @property string $type
 * @property integer $objectId
 * @property string $comment
 * @property string $effDt
 *
 * @property Party $party
 */
abstract class BasePartyLocator extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyLocator';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Locator|Party Locators', $n);
	}

	public static function representingColumn() {
		return 'class';
	}

	public function rules() {
		return array(
			array('Party_id', 'required'),
			array('Party_id, objectId', 'numerical', 'integerOnly'=>true),
			array('class, type', 'length', 'max'=>255),
			array('comment, effDt', 'safe'),
			array('class, type, objectId, comment, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, class, type, objectId, comment, effDt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                			'class' => yii::t('app', 'Class'),
                			'type' => yii::t('app', 'Type'),
                			'objectId' => yii::t('app', 'Object Id'),
                			'comment' => yii::t('app', 'Comment'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('class', $this->class, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('objectId', $this->objectId);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('effDt', $this->effDt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}