<?php

/**
 * This is the model base class for the table "PartyMail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyMail".
 *
 * Columns in table "PartyMail" available as properties of the model,
 * followed by relations of table "PartyMail" available as properties of the model.
 *
 * @property integer $id
 * @property string $value
 * @property integer $active
 * @property string $effDt
 * @property integer $Party_id
 * @property integer $PartyMailType_id
 *
 * @property Party $party
 * @property PartyMailType $partyMailType
 */
abstract class BasePartyMail extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyMail';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Mail|Party Mails', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function relations() {
		$relations = array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'partyMailType' => array(self::BELONGS_TO, 'PartyMailType', 'PartyMailType_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Party_id, PartyMailType_id', 'required'),
			array('active, Party_id, PartyMailType_id', 'numerical', 'integerOnly'=>true),
			array('value', 'length', 'max'=>255),
			array('effDt', 'safe'),
			array('value, active, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, value, active, effDt, Party_id, PartyMailType_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('effDt', $this->effDt, true);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('PartyMailType_id', $this->PartyMailType_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
                        'sort' => array(
                            'defaultOrder' => array(
                                $this->representingColumn() => CSort::SORT_ASC
                            )
                        )
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'value' => yii::t('app', 'Value'),
                			'active' => yii::t('app', 'Active'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'PartyMailType_id' => yii::t('app', 'Party Mail Type'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'partyMailType' => yii::t('app', 'Party Mail Type'),
		);
	}
}