<?php

/**
 * This is the model base class for the table "Country".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Country".
 *
 * Columns in table "Country" available as properties of the model,
 * followed by relations of table "Country" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $active
 *
 * @property State[] $states
 */
abstract class BaseCountry extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Country';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Country|Countries', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function relations() {
		$relations = array(
			'states' => array(self::HAS_MANY, 'State', 'Country_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('code', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>45),
			array('name', 'safe'),
			array('name, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, active', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
                			'name' => yii::t('app', 'Name'),
                			'active' => yii::t('app', 'Active'),
                        			                        'states' => yii::t('app', 'States'),
		);
	}
}