<?php

/**
 * This is the model base class for the table "Name".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Name".
 *
 * Columns in table "Name" available as properties of the model,
 * followed by relations of table "Name" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $surName
 * @property string $motherFamilyName
 * @property string $firstName
 * @property string $secondName
 * @property string $md5
 * @property string $effDt
 *
 * @property PartyName[] $partyNames
 */
abstract class BaseName extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Name';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Name|Names', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('md5', 'length', 'max'=>32),
			array('name, surName, motherFamilyName, firstName, secondName, effDt', 'safe'),
			array('name, surName, motherFamilyName, firstName, secondName, md5, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, surName, motherFamilyName, firstName, secondName, md5, effDt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
			'partyNames' => array(self::HAS_MANY, 'PartyName', 'Name_id'),
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'surName' => yii::t('app', 'Sur Name'),
                			'motherFamilyName' => yii::t('app', 'Mother Family Name'),
                			'firstName' => yii::t('app', 'First Name'),
                			'secondName' => yii::t('app', 'Second Name'),
                			'md5' => yii::t('app', 'Md5'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'partyNames' => yii::t('app', 'Party Names'),
		);
	}
}