<?php

/**
 * This is the model base class for the table "CrudLog".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CrudLog".
 *
 * Columns in table "CrudLog" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $model
 * @property integer $modelId
 * @property string $action
 * @property string $effDt
 *
 */
abstract class BaseCrudLog extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CrudLog';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Crud Log|Crud Logs', $n);
	}

	public static function representingColumn() {
		return 'model';
	}

	public function rules() {
		return array(
			array('modelId', 'numerical', 'integerOnly'=>true),
			array('model', 'length', 'max'=>255),
			array('action', 'length', 'max'=>45),
			array('effDt', 'safe'),
			array('model, modelId, action, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, model, modelId, action, effDt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'model' => yii::t('app', 'Model'),
                			'modelId' => yii::t('app', 'Model Id'),
                			'action' => yii::t('app', 'Action'),
                			'effDt' => yii::t('app', 'Eff Dt'),
		);
	}
}