<?php

/**
 * This is the model base class for the table "PhoneNbr".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PhoneNbr".
 *
 * Columns in table "PhoneNbr" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $value
 * @property string $ext
 *
 */
abstract class BasePhoneNbr extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PhoneNbr';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Phone Nbr|Phone Nbrs', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('value, ext', 'length', 'max'=>255),
			array('value, ext', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, value, ext', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'value' => yii::t('app', 'Value'),
                			'ext' => yii::t('app', 'Ext'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('ext', $this->ext, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}