<?php

/**
 * This is the model base class for the table "EavCode".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EavCode".
 *
 * Columns in table "EavCode" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 *
 */
abstract class BaseEavCode extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'EavCode';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Eav Code|Eav Codes', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code', 'length', 'max'=>255),
			array('code', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}