<?php

/**
 * This is the model base class for the table "PartyMailType".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyMailType".
 *
 * Columns in table "PartyMailType" available as properties of the model,
 * followed by relations of table "PartyMailType" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $text
 *
 * @property PartyMail[] $partyMails
 */
abstract class BasePartyMailType extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyMailType';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Mail Type|Party Mail Types', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function relations() {
		$relations = array(
			'partyMails' => array(self::HAS_MANY, 'PartyMail', 'PartyMailType_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('code, text', 'length', 'max'=>45),
			array('code, text', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, text', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('text', $this->text, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
                        'sort' => array(
                            'defaultOrder' => array(
                                $this->representingColumn() => CSort::SORT_ASC
                            )
                        )
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
                			'text' => yii::t('app', 'Text'),
                        			                        'partyMails' => yii::t('app', 'Party Mails'),
		);
	}
}