<?php

/**
 * This is the model base class for the table "CfdParty".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdParty".
 *
 * Columns in table "CfdParty" available as properties of the model,
 * followed by relations of table "CfdParty" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Cfd_id
 * @property integer $Party_id
 * @property string $type
 *
 * @property Cfd $cfd
 * @property Party $party
 */
abstract class BaseCfdParty extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdParty';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Party|Cfd Parties', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function relations() {
		$relations = array(
			'cfd' => array(self::BELONGS_TO, 'Cfd', 'Cfd_id'),
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Cfd_id, Party_id', 'required'),
			array('Cfd_id, Party_id', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>45),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Cfd_id, Party_id, type', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Cfd_id', $this->Cfd_id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Cfd_id' => yii::t('app', 'Cfd'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                			'type' => yii::t('app', 'Type'),
                        			                        'cfd' => yii::t('app', 'Cfd'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}
}