<?php

/**
 * This is the model base class for the table "FileAsset".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FileAsset".
 *
 * Columns in table "FileAsset" available as properties of the model,
 * followed by relations of table "FileAsset" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $location
 * @property string $creationDttm
 *
 * @property ObjectHasFileAsset[] $objectHasFileAssets
 */
abstract class BaseFileAsset extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'FileAsset';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'File Asset|File Assets', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, location, creationDttm', 'safe'),
			array('name, location, creationDttm', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, location, creationDttm', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
			'objectHasFileAssets' => array(self::HAS_MANY, 'ObjectHasFileAsset', 'FileAsset_id'),
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'location' => yii::t('app', 'Location'),
                			'creationDttm' => yii::t('app', 'Creation Dttm'),
                        			                        'objectHasFileAssets' => yii::t('app', 'Object Has File Assets'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('creationDttm', $this->creationDttm, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}