<?php

/**
 * This is the model base class for the table "PartyPaymentMethod".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyPaymentMethod".
 *
 * Columns in table "PartyPaymentMethod" available as properties of the model,
 * followed by relations of table "PartyPaymentMethod" available as properties of the model.
 *
 * @property integer $id
 * @property string $method
 * @property string $bankAcct
 * @property integer $active
 * @property string $effDt
 * @property integer $Party_id
 *
 * @property Party $party
 */
abstract class BasePartyPaymentMethod extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyPaymentMethod';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Payment Method|Party Payment Methods', $n);
	}

	public static function representingColumn() {
		return 'method';
	}

	public function relations() {
		$relations = array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Party_id', 'required'),
			array('active, Party_id', 'numerical', 'integerOnly'=>true),
			array('method, bankAcct, effDt', 'safe'),
			array('method, bankAcct, active, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, method, bankAcct, active, effDt, Party_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('method', $this->method, true);
		$criteria->compare('bankAcct', $this->bankAcct, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('effDt', $this->effDt, true);
		$criteria->compare('Party_id', $this->Party_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
                        'sort' => array(
                            'defaultOrder' => array(
                                $this->representingColumn() => CSort::SORT_ASC
                            )
                        )
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'method' => yii::t('app', 'Method'),
                			'bankAcct' => yii::t('app', 'Bank Acct'),
                			'active' => yii::t('app', 'Active'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}
}