<?php

/**
 * This is the model base class for the table "Brand".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Brand".
 *
 * Columns in table "Brand" available as properties of the model,
 * followed by relations of table "Brand" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $Party_id
 *
 * @property Party $party
 */
abstract class BaseBrand extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Brand';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Brand|Brands', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, Party_id', 'required'),
			array('Party_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('id, name, Party_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}

    public function defaultScope() {
        return array('order' => BaseBrand::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('Party_id', $this->Party_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}