<?php

/**
 * This is the model base class for the table "CfdPaymentMethod".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdPaymentMethod".
 *
 * Columns in table "CfdPaymentMethod" available as properties of the model,
 * followed by relations of table "CfdPaymentMethod" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $bankAcctNbr
 *
 * @property Cfd[] $cfds
 */
abstract class BaseCfdPaymentMethod extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdPaymentMethod';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Payment Method|Cfd Payment Methods', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function relations() {
		$relations = array(
			'cfds' => array(self::HAS_MANY, 'Cfd', 'CfdPaymentMethod_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('name, bankAcctNbr', 'safe'),
			array('name, bankAcctNbr', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, bankAcctNbr', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('bankAcctNbr', $this->bankAcctNbr, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'bankAcctNbr' => yii::t('app', 'Bank Acct Nbr'),
                        			                        'cfds' => yii::t('app', 'Cfds'),
		);
	}
}