<?php

/**
 * This is the model base class for the table "Entity".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Entity".
 *
 * Columns in table "Entity" available as properties of the model,
 * followed by relations of table "Entity" available as properties of the model.
 *
 * @property integer $id
 * @property string $class
 *
 * @property Eav[] $eavs
 */
abstract class BaseEntity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Entity';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Entity|Entities', $n);
	}

	public static function representingColumn() {
		return 'class';
	}

	public function rules() {
		return array(
			array('class', 'length', 'max'=>45),
			array('class', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, class', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'eavs' => array(self::HAS_MANY, 'Eav', 'Entity_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'class' => yii::t('app', 'Class'),
                        			                        'eavs' => yii::t('app', 'Eavs'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('class', $this->class, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}