<?php

/**
 * This is the model base class for the table "Party".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Party".
 *
 * Columns in table "Party" available as properties of the model,
 * followed by relations of table "Party" available as properties of the model.
 *
 * @property integer $id
 * @property integer $person
 *
 * @property CfdHasParty[] $cfdHasParties
 * @property PartyAttribute[] $partyAttributes
 * @property PartyHasIdentifiers[] $partyHasIdentifiers
 * @property PartyHasRelationship[] $partyHasRelationships
 * @property PartyHasRelationship[] $partyHasRelationships1
 * @property PartyIdentifier[] $partyIdentifiers
 * @property PartyLocator[] $partyLocators
 * @property PartyName[] $partyNames
 * @property SatCertificate[] $satCertificates
 */
abstract class BaseParty extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Party';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party|Parties', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person', 'numerical', 'integerOnly'=>true),
			array('person', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, person', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cfdHasParties' => array(self::HAS_MANY, 'CfdHasParty', 'Party_id'),
			'partyAttributes' => array(self::HAS_MANY, 'PartyAttribute', 'Party_id'),
			'partyHasIdentifiers' => array(self::HAS_MANY, 'PartyHasIdentifiers', 'Party_id'),
			'partyHasRelationships' => array(self::HAS_MANY, 'PartyHasRelationship', 'Party_id'),
			'partyHasRelationships1' => array(self::HAS_MANY, 'PartyHasRelationship', 'RelatedParty_id'),
			'partyIdentifiers' => array(self::HAS_MANY, 'PartyIdentifier', 'Party_id'),
			'partyLocators' => array(self::HAS_MANY, 'PartyLocator', 'Party_id'),
			'partyNames' => array(self::HAS_MANY, 'PartyName', 'Party_id'),
			'satCertificates' => array(self::MANY_MANY, 'SatCertificate', 'Party_has_SatCertificate(Party_id, SatCertificate_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'satCertificates' => 'PartyHasSatCertificate',
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'person' => yii::t('app', 'Person'),
                        			                        'cfdHasParties' => yii::t('app', 'Cfd Has Parties'),
                        			                        'partyAttributes' => yii::t('app', 'Party Attributes'),
                        			                        'partyHasIdentifiers' => yii::t('app', 'Party Has Identifiers'),
                        			                        'partyHasRelationships' => yii::t('app', 'Party Has Relationships'),
                        			                        'partyHasRelationships1' => yii::t('app', 'Party Has Relationships1'),
                        			                        'partyIdentifiers' => yii::t('app', 'Party Identifiers'),
                        			                        'partyLocators' => yii::t('app', 'Party Locators'),
                        			                        'partyNames' => yii::t('app', 'Party Names'),
                        			                        'satCertificates' => yii::t('app', 'Sat Certificates'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person', $this->person);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}