<?php

/**
 * This is the model base class for the table "PartyName".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyName".
 *
 * Columns in table "PartyName" available as properties of the model,
 * followed by relations of table "PartyName" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property string $surName
 * @property string $motherName
 * @property string $firstName
 * @property string $secondName
 * @property string $effDt
 *
 * @property Party $party
 */
abstract class BasePartyName extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyName';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Name|Party Names', $n);
	}

	public static function representingColumn() {
		return 'effDt';
	}

	public function rules() {
		return array(
			array('Party_id, effDt', 'required'),
			array('Party_id', 'numerical', 'integerOnly'=>true),
			array('surName, motherName, firstName, secondName', 'safe'),
			array('surName, motherName, firstName, secondName', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, surName, motherName, firstName, secondName, effDt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                			'surName' => yii::t('app', 'Sur Name'),
                			'motherName' => yii::t('app', 'Mother Name'),
                			'firstName' => yii::t('app', 'First Name'),
                			'secondName' => yii::t('app', 'Second Name'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('surName', $this->surName, true);
		$criteria->compare('motherName', $this->motherName, true);
		$criteria->compare('firstName', $this->firstName, true);
		$criteria->compare('secondName', $this->secondName, true);
		$criteria->compare('effDt', $this->effDt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}