<?php

/**
 * This is the model base class for the table "Party_has_SatCertificate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyHasSatCertificate".
 *
 * Columns in table "Party_has_SatCertificate" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Party_id
 * @property integer $SatCertificate_id
 *
 */
abstract class BasePartyHasSatCertificate extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Party_has_SatCertificate';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Has Sat Certificate|Party Has Sat Certificates', $n);
	}

	public static function representingColumn() {
		return array(
			'Party_id',
			'SatCertificate_id',
		);
	}

	public function rules() {
		return array(
			array('Party_id, SatCertificate_id', 'required'),
			array('Party_id, SatCertificate_id', 'numerical', 'integerOnly'=>true),
			array('Party_id, SatCertificate_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'SatCertificate_id' => yii::t('app', 'Sat Certificate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('SatCertificate_id', $this->SatCertificate_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}