<?php

/**
 * This is the model base class for the table "PartyRelationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyRelationship".
 *
 * Columns in table "PartyRelationship" available as properties of the model,
 * followed by relations of table "PartyRelationship" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property integer $PartyRelationshipType_id
 * @property integer $RelatedParty_id
 *
 * @property Party $party
 * @property PartyRelationshipType $partyRelationshipType
 * @property Party $relatedParty
 */
abstract class BasePartyRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyRelationship';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Relationship|Party Relationships', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('Party_id, PartyRelationshipType_id, RelatedParty_id', 'required'),
			array('Party_id, PartyRelationshipType_id, RelatedParty_id', 'numerical', 'integerOnly'=>true),
			array('id, Party_id, PartyRelationshipType_id, RelatedParty_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'partyRelationshipType' => array(self::BELONGS_TO, 'PartyRelationshipType', 'PartyRelationshipType_id'),
			'relatedParty' => array(self::BELONGS_TO, 'Party', 'RelatedParty_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'PartyRelationshipType_id' => yii::t('app', 'Party Relationship Type'),
                        			                        'RelatedParty_id' => yii::t('app', 'Related Party'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'partyRelationshipType' => yii::t('app', 'Party Relationship Type'),
                        			                        'relatedParty' => yii::t('app', 'Related Party'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BasePartyRelationship::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('PartyRelationshipType_id', $this->PartyRelationshipType_id);
		$criteria->compare('RelatedParty_id', $this->RelatedParty_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}