<?php

/**
 * This is the model base class for the table "ObjectHasFileAsset".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ObjectHasFileAsset".
 *
 * Columns in table "ObjectHasFileAsset" available as properties of the model,
 * followed by relations of table "ObjectHasFileAsset" available as properties of the model.
 *
 * @property integer $id
 * @property integer $FileAsset_id
 * @property string $type
 * @property string $objectName
 * @property integer $objectId
 *
 * @property FileAsset $fileAsset
 */
abstract class BaseObjectHasFileAsset extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ObjectHasFileAsset';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Object Has File Asset|Object Has File Assets', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('FileAsset_id', 'required'),
			array('FileAsset_id, objectId', 'numerical', 'integerOnly'=>true),
			array('type, objectName', 'length', 'max'=>255),
			array('type, objectName, objectId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, FileAsset_id, type, objectName, objectId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
			'fileAsset' => array(self::BELONGS_TO, 'FileAsset', 'FileAsset_id'),
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'FileAsset_id' => yii::t('app', 'File Asset'),
                			'type' => yii::t('app', 'Type'),
                			'objectName' => yii::t('app', 'Object Name'),
                			'objectId' => yii::t('app', 'Object Id'),
                        			                        'fileAsset' => yii::t('app', 'File Asset'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('FileAsset_id', $this->FileAsset_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('objectName', $this->objectName, true);
		$criteria->compare('objectId', $this->objectId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}