<?php

/**
 * This is the model base class for the table "AutomobileTrim".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AutomobileTrim".
 *
 * Columns in table "AutomobileTrim" available as properties of the model,
 * followed by relations of table "AutomobileTrim" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $AutomobileModel_id
 *
 * @property Automobile[] $automobiles
 * @property AutomobileModel $automobileModel
 */
abstract class BaseAutomobileTrim extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'AutomobileTrim';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Automobile Trim|Automobile Trims', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, AutomobileModel_id', 'required'),
			array('AutomobileModel_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('id, name, AutomobileModel_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'automobiles' => array(self::HAS_MANY, 'Automobile', 'AutomobileTrim_id'),
			'automobileModel' => array(self::BELONGS_TO, 'AutomobileModel', 'AutomobileModel_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                        			                        'AutomobileModel_id' => yii::t('app', 'Automobile Model'),
                        			                        'automobiles' => yii::t('app', 'Automobiles'),
                        			                        'automobileModel' => yii::t('app', 'Automobile Model'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BaseAutomobileTrim::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('AutomobileModel_id', $this->AutomobileModel_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}