<?php

/**
 * This is the model base class for the table "SatFoliosCfd".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SatFoliosCfd".
 *
 * Columns in table "SatFoliosCfd" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $rfc
 * @property integer $approvalNbr
 * @property integer $approvalYear
 * @property string $serial
 * @property integer $startFolio
 * @property integer $endFolio
 * @property string $md5
 *
 */
abstract class BaseSatFoliosCfd extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'SatFoliosCfd';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Sat Folios Cfd|Sat Folios Cfds', $n);
	}

	public static function representingColumn() {
		return 'rfc';
	}

	public function rules() {
		return array(
			array('approvalNbr, approvalYear, startFolio, endFolio', 'numerical', 'integerOnly'=>true),
			array('rfc', 'length', 'max'=>13),
			array('md5', 'length', 'max'=>45),
			array('serial', 'safe'),
			array('rfc, approvalNbr, approvalYear, serial, startFolio, endFolio, md5', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, rfc, approvalNbr, approvalYear, serial, startFolio, endFolio, md5', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'rfc' => yii::t('app', 'Rfc'),
                			'approvalNbr' => yii::t('app', 'Approval Nbr'),
                			'approvalYear' => yii::t('app', 'Approval Year'),
                			'serial' => yii::t('app', 'Serial'),
                			'startFolio' => yii::t('app', 'Start Folio'),
                			'endFolio' => yii::t('app', 'End Folio'),
                			'md5' => yii::t('app', 'Md5'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BaseSatFoliosCfd::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('rfc', $this->rfc, true);
		$criteria->compare('approvalNbr', $this->approvalNbr);
		$criteria->compare('approvalYear', $this->approvalYear);
		$criteria->compare('serial', $this->serial, true);
		$criteria->compare('startFolio', $this->startFolio);
		$criteria->compare('endFolio', $this->endFolio);
		$criteria->compare('md5', $this->md5, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}