<?php

/**
 * This is the model base class for the table "Color".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Color".
 *
 * Columns in table "Color" available as properties of the model,
 * followed by relations of table "Color" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $htmlCode
 * @property integer $active
 *
 * @property AutomobileAvailableColor[] $automobileAvailableColors
 */
abstract class BaseColor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Color';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Color|Colors', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name, htmlCode', 'length', 'max'=>45),
			array('htmlCode, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, htmlCode, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'automobileAvailableColors' => array(self::HAS_MANY, 'AutomobileAvailableColor', 'Color_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                			'htmlCode' => yii::t('app', 'Html Code'),
                			'active' => yii::t('app', 'Active'),
                        			                        'automobileAvailableColors' => yii::t('app', 'Automobile Available Colors'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BaseColor::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('htmlCode', $this->htmlCode, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}