<?php

/**
 * This is the model base class for the table "PartyHasRole".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyHasRole".
 *
 * Columns in table "PartyHasRole" available as properties of the model,
 * followed by relations of table "PartyHasRole" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property integer $PartyRole_id
 * @property string $effDt
 * @property integer $active
 *
 * @property Party $party
 * @property PartyRole $partyRole
 */
abstract class BasePartyHasRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyHasRole';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Has Role|Party Has Roles', $n);
	}

	public static function representingColumn() {
		return 'effDt';
	}

	public function rules() {
		return array(
			array('Party_id, PartyRole_id', 'required'),
			array('Party_id, PartyRole_id, active', 'numerical', 'integerOnly'=>true),
			array('effDt', 'safe'),
			array('effDt, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, PartyRole_id, effDt, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'partyRole' => array(self::BELONGS_TO, 'PartyRole', 'PartyRole_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'PartyRole_id' => yii::t('app', 'Party Role'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                			'active' => yii::t('app', 'Active'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'partyRole' => yii::t('app', 'Party Role'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BasePartyHasRole::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('PartyRole_id', $this->PartyRole_id);
		$criteria->compare('effDt', $this->effDt, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}