<?php

/**
 * This is the model base class for the table "PartyHasRelationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyHasRelationship".
 *
 * Columns in table "PartyHasRelationship" available as properties of the model,
 * followed by relations of table "PartyHasRelationship" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property integer $RelatedParty_id
 * @property string $type
 *
 * @property Party $party
 * @property Party $relatedParty
 */
abstract class BasePartyHasRelationship extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyHasRelationship';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Has Relationship|Party Has Relationships', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('Party_id, RelatedParty_id', 'required'),
			array('Party_id, RelatedParty_id', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>45),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, RelatedParty_id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'relatedParty' => array(self::BELONGS_TO, 'Party', 'RelatedParty_id'),
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'RelatedParty_id' => yii::t('app', 'Related Party'),
                			'type' => yii::t('app', 'Type'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'relatedParty' => yii::t('app', 'Related Party'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('RelatedParty_id', $this->RelatedParty_id);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}