<?php

/**
 * This is the model base class for the table "Eav".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Eav".
 *
 * Columns in table "Eav" available as properties of the model,
 * followed by relations of table "Eav" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Entity_id
 * @property string $attribute
 * @property string $value
 * @property string $effDt
 *
 * @property Entity $entity
 */
abstract class BaseEav extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Eav';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Eav|Eavs', $n);
	}

	public static function representingColumn() {
		return 'attribute';
	}

	public function rules() {
		return array(
			array('Entity_id', 'required'),
			array('Entity_id', 'numerical', 'integerOnly'=>true),
			array('attribute', 'length', 'max'=>45),
			array('value, effDt', 'safe'),
			array('attribute, value, effDt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Entity_id, attribute, value, effDt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'entity' => array(self::BELONGS_TO, 'Entity', 'Entity_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Entity_id' => yii::t('app', 'Entity'),
                			'attribute' => yii::t('app', 'Attribute'),
                			'value' => yii::t('app', 'Value'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'entity' => yii::t('app', 'Entity'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Entity_id', $this->Entity_id);
		$criteria->compare('attribute', $this->attribute, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('effDt', $this->effDt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}