<?php

/**
 * This is the model base class for the table "ModelAttribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModelAttribute".
 *
 * Columns in table "ModelAttribute" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $model
 * @property integer $modelId
 * @property string $code
 * @property string $value
 *
 */
abstract class BaseModelAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ModelAttribute';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Model Attribute|Model Attributes', $n);
	}

	public static function representingColumn() {
		return 'model';
	}

	public function rules() {
		return array(
			array('modelId', 'numerical', 'integerOnly'=>true),
			array('model, code', 'length', 'max'=>45),
			array('value', 'safe'),
			array('model, modelId, code, value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, model, modelId, code, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'model' => yii::t('app', 'Model'),
                			'modelId' => yii::t('app', 'Model Id'),
                			'code' => yii::t('app', 'Code'),
                			'value' => yii::t('app', 'Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('model', $this->model, true);
		$criteria->compare('modelId', $this->modelId);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}