<?php

/**
 * This is the model base class for the table "CfdAttribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdAttribute".
 *
 * Columns in table "CfdAttribute" available as properties of the model,
 * followed by relations of table "CfdAttribute" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Cfd_id
 * @property string $code
 * @property string $value
 *
 * @property Cfd $cfd
 */
abstract class BaseCfdAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdAttribute';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Attribute|Cfd Attributes', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('Cfd_id, code', 'required'),
			array('Cfd_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>45),
			array('value', 'safe'),
			array('value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Cfd_id, code, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cfd' => array(self::BELONGS_TO, 'Cfd', 'Cfd_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Cfd_id' => yii::t('app', 'Cfd'),
                			'code' => yii::t('app', 'Code'),
                			'value' => yii::t('app', 'Value'),
                        			                        'cfd' => yii::t('app', 'Cfd'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Cfd_id', $this->Cfd_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}