<?php

/**
 * This is the model base class for the table "MasterAccountAttribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MasterAccountAttribute".
 *
 * Columns in table "MasterAccountAttribute" available as properties of the model,
 * followed by relations of table "MasterAccountAttribute" available as properties of the model.
 *
 * @property integer $id
 * @property integer $MasterAccount_id
 * @property string $code
 * @property string $description
 * @property string $value
 *
 * @property MasterAccount $masterAccount
 */
abstract class BaseMasterAccountAttribute extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'MasterAccountAttribute';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Master Account Attribute|Master Account Attributes', $n);
    }

    public static function representingColumn() {
        return 'code';
    }

    public function rules() {
        return array(
            array('MasterAccount_id, code, description', 'required'),
            array('MasterAccount_id', 'numerical', 'integerOnly' => true),
            array('code', 'length', 'max' => 255),
            array('value', 'safe'),
            array('value', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, MasterAccount_id, code, description, value', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'masterAccount' => array(self::BELONGS_TO, 'MasterAccount', 'MasterAccount_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => yii::t('app', 'Id'),
            'MasterAccount_id' => yii::t('app', 'Master Account'),
            'code' => yii::t('app', 'Code'),
            'description' => yii::t('app', 'Description'),
            'value' => yii::t('app', 'Value'),
            'masterAccount' => yii::t('app', 'Master Account'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('MasterAccount_id', $this->MasterAccount_id);
        $criteria->compare('code', $this->code, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('value', $this->value, true);

        return new CActiveDataProvider($this, array(
                    'criteria' => $criteria,
                ));
    }

}