<?php

/**
 * This is the model base class for the table "PartyAddress".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyAddress".
 *
 * Columns in table "PartyAddress" available as properties of the model,
 * followed by relations of table "PartyAddress" available as properties of the model.
 *
 * @property integer $id
 * @property integer $type
 * @property integer $Party_id
 * @property integer $Address_id
 * @property string $reference
 *
 * @property Address $address
 * @property Party $party
 */
abstract class BasePartyAddress extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyAddress';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Address|Party Addresses', $n);
	}

	public static function representingColumn() {
		return 'reference';
	}

	public function rules() {
		return array(
			array('type, Party_id, Address_id', 'required'),
			array('type, Party_id, Address_id', 'numerical', 'integerOnly'=>true),
			array('reference', 'safe'),
			array('reference', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type, Party_id, Address_id, reference', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'address' => array(self::BELONGS_TO, 'Address', 'Address_id'),
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'type' => yii::t('app', 'Type'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'Address_id' => yii::t('app', 'Address'),
                			'reference' => yii::t('app', 'Reference'),
                        			                        'address' => yii::t('app', 'Address'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('Address_id', $this->Address_id);
		$criteria->compare('reference', $this->reference, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}