<?php

/**
 * This is the model base class for the table "Currency".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Currency".
 *
 * Columns in table "Currency" available as properties of the model,
 * followed by relations of table "Currency" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $plural
 * @property string $symbol
 * @property integer $active
 *
 * @property Cfd[] $cfds
 */
abstract class BaseCurrency extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Currency';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Currency|Currencies', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function relations() {
		$relations = array(
			'cfds' => array(self::HAS_MANY, 'Cfd', 'Currency_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('active', 'numerical', 'integerOnly'=>true),
			array('code, symbol', 'length', 'max'=>45),
			array('name, plural', 'safe'),
			array('code, name, plural, symbol, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, plural, symbol, active', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('plural', $this->plural, true);
		$criteria->compare('symbol', $this->symbol, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
                			'name' => yii::t('app', 'Name'),
                			'plural' => yii::t('app', 'Plural'),
                			'symbol' => yii::t('app', 'Symbol'),
                			'active' => yii::t('app', 'Active'),
                        			                        'cfds' => yii::t('app', 'Cfds'),
		);
	}
}