<?php

/**
 * This is the model base class for the table "CfdAddress".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdAddress".
 *
 * Columns in table "CfdAddress" available as properties of the model,
 * followed by relations of table "CfdAddress" available as properties of the model.
 *
 * @property integer $id
 * @property integer $type
 * @property integer $Cfd_id
 * @property integer $Address_id
 * @property string $reference
 *
 * @property Cfd $cfd
 * @property Address $address
 */
abstract class BaseCfdAddress extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdAddress';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Address|Cfd Addresses', $n);
	}

	public static function representingColumn() {
		return 'reference';
	}

	public function rules() {
		return array(
			array('type, Cfd_id, Address_id', 'required'),
			array('type, Cfd_id, Address_id', 'numerical', 'integerOnly'=>true),
			array('reference', 'safe'),
			array('reference', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type, Cfd_id, Address_id, reference', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cfd' => array(self::BELONGS_TO, 'Cfd', 'Cfd_id'),
			'address' => array(self::BELONGS_TO, 'Address', 'Address_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'type' => yii::t('app', 'Type'),
                        			                        'Cfd_id' => yii::t('app', 'Cfd'),
                        			                        'Address_id' => yii::t('app', 'Address'),
                			'reference' => yii::t('app', 'Reference'),
                        			                        'cfd' => yii::t('app', 'Cfd'),
                        			                        'address' => yii::t('app', 'Address'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type);
		$criteria->compare('Cfd_id', $this->Cfd_id);
		$criteria->compare('Address_id', $this->Address_id);
		$criteria->compare('reference', $this->reference, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}