<?php

/**
 * This is the model base class for the table "CfdItem_has_CustomsPermit".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdItemHasCustomsPermit".
 *
 * Columns in table "CfdItem_has_CustomsPermit" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $CfdItem_id
 * @property integer $CustomsPermit_id
 *
 */
abstract class BaseCfdItemHasCustomsPermit extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdItem_has_CustomsPermit';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Item Has Customs Permit|Cfd Item Has Customs Permits', $n);
	}

	public static function representingColumn() {
		return array(
			'CfdItem_id',
			'CustomsPermit_id',
		);
	}

	public function relations() {
		$relations = array(
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('CfdItem_id, CustomsPermit_id', 'required'),
			array('CfdItem_id, CustomsPermit_id', 'numerical', 'integerOnly'=>true),
			array('CfdItem_id, CustomsPermit_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('CfdItem_id', $this->CfdItem_id);
		$criteria->compare('CustomsPermit_id', $this->CustomsPermit_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                        			                        'CfdItem_id' => yii::t('app', 'Cfd Item'),
                        			                        'CustomsPermit_id' => yii::t('app', 'Customs Permit'),
		);
	}
}