<?php

/**
 * This is the model base class for the table "CfdAddressType".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CfdAddressType".
 *
 * Columns in table "CfdAddressType" available as properties of the model,
 * followed by relations of table "CfdAddressType" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 *
 * @property CfdAddress[] $cfdAddresses
 */
abstract class BaseCfdAddressType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CfdAddressType';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd Address Type|Cfd Address Types', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, name', 'required'),
			array('code', 'length', 'max'=>45),
			array('id, code, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cfdAddresses' => array(self::HAS_MANY, 'CfdAddress', 'CfdAddressType_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
                			'name' => yii::t('app', 'Name'),
                        			                        'cfdAddresses' => yii::t('app', 'Cfd Addresses'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}