<?php

/**
 * This is the model base class for the table "SwTest".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SwTest".
 *
 * Columns in table "SwTest" available as properties of the model,
 * followed by relations of table "SwTest" available as properties of the model.
 *
 * @property integer $id
 * @property string $status
 *
 * @property ObjectHasFileAsset[] $objectHasFileAssets
 */
abstract class BaseSwTest extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'SwTest';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Sw Test|Sw Tests', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('status', 'length', 'max'=>45),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$relations = array(
			'objectHasFileAssets' => array(self::HAS_MANY, 'ObjectHasFileAsset', 'SwTest_id'),
		);
                return array_merge($relations, parent::relations());
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'status' => yii::t('app', 'Status'),
                        			                        'objectHasFileAssets' => yii::t('app', 'Object Has File Assets'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}