<?php

/**
 * This is the model base class for the table "PartyAttribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PartyAttribute".
 *
 * Columns in table "PartyAttribute" available as properties of the model,
 * followed by relations of table "PartyAttribute" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property string $code
 * @property string $value
 *
 * @property Party $party
 */
abstract class BasePartyAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PartyAttribute';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Party Attribute|Party Attributes', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('Party_id', 'required'),
			array('Party_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>45),
			array('value', 'safe'),
			array('code, value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, code, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                			'code' => yii::t('app', 'Code'),
                			'value' => yii::t('app', 'Value'),
                        			                        'party' => yii::t('app', 'Party'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}