<?php

/**
 * This is the model base class for the table "RelatedParty".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RelatedParty".
 *
 * Columns in table "RelatedParty" available as properties of the model,
 * followed by relations of table "RelatedParty" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Party_id
 * @property integer $RelatedParty_id
 * @property integer $Role_id
 * @property integer $enabled
 * @property string $effDt
 * @property integer $Identifier_id
 *
 * @property Identifier $identifier
 * @property Party $party
 * @property Party $relatedParty
 * @property Role $role
 */
abstract class BaseRelatedParty extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'RelatedParty';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Related Party|Related Parties', $n);
	}

	public static function representingColumn() {
		return 'effDt';
	}

	public function relations() {
		$relations = array(
			'identifier' => array(self::BELONGS_TO, 'Identifier', 'Identifier_id'),
			'party' => array(self::BELONGS_TO, 'Party', 'Party_id'),
			'relatedParty' => array(self::BELONGS_TO, 'Party', 'RelatedParty_id'),
			'role' => array(self::BELONGS_TO, 'Role', 'Role_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Party_id, RelatedParty_id, Role_id, effDt, Identifier_id', 'required'),
			array('Party_id, RelatedParty_id, Role_id, enabled, Identifier_id', 'numerical', 'integerOnly'=>true),
			array('enabled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Party_id, RelatedParty_id, Role_id, enabled, effDt, Identifier_id', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Party_id', $this->Party_id);
		$criteria->compare('RelatedParty_id', $this->RelatedParty_id);
		$criteria->compare('Role_id', $this->Role_id);
		$criteria->compare('enabled', $this->enabled);
		$criteria->compare('effDt', $this->effDt, true);
		$criteria->compare('Identifier_id', $this->Identifier_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Party_id' => yii::t('app', 'Party'),
                        			                        'RelatedParty_id' => yii::t('app', 'Related Party'),
                        			                        'Role_id' => yii::t('app', 'Role'),
                			'enabled' => yii::t('app', 'Enabled'),
                			'effDt' => yii::t('app', 'Eff Dt'),
                        			                        'Identifier_id' => yii::t('app', 'Identifier'),
                        			                        'identifier' => yii::t('app', 'Identifier'),
                        			                        'party' => yii::t('app', 'Party'),
                        			                        'relatedParty' => yii::t('app', 'Related Party'),
                        			                        'role' => yii::t('app', 'Role'),
		);
	}
}