<?php

/**
 * This is the model base class for the table "Cfd".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cfd".
 *
 * Columns in table "Cfd" available as properties of the model,
 * followed by relations of table "Cfd" available as properties of the model.
 *
 * @property integer $id
 * @property string $invoice
 * @property string $version
 * @property string $serial
 * @property integer $folio
 * @property string $uuid
 * @property string $dttm
 * @property string $seal
 * @property string $paymentType
 * @property string $paymentTerm
 * @property string $exchangeRate
 * @property string $currency
 * @property integer $Currency_id
 * @property string $voucherType
 * @property string $paymentMethod
 * @property string $expeditionPlace
 * @property string $paymentAcctNbr
 * @property integer $sourceFolio
 * @property string $sourceSerial
 * @property string $sourceDttm
 * @property string $sourceAmt
 * @property string $dtsVersion
 * @property string $dtsDttm
 * @property string $dtsSatCertNbr
 * @property string $dtsSatSeal
 * @property string $dtsOriginalString
 * @property integer $approvalNbr
 * @property integer $approvalYear
 * @property string $md5
 * @property string $creationDt
 * @property string $updateDt
 * @property integer $vendorParty_id
 * @property integer $customerParty_id
 * @property string $originalString
 * @property string $cbb
 * @property integer $SatCertificate_id
 * @property integer $dtsSatCertificate_id
 * @property integer $CfdStatus_id
 * @property string $errorMsg
 * @property integer $PaymentTerm_id
 * @property string $addenda
 *
 * @property CfdStatus $cfdStatus
 * @property Currency $currency0
 * @property Party $vendorParty
 * @property Party $customerParty
 * @property PaymentTerm $paymentTerm0
 * @property SatCertificate $satCertificate
 * @property SatCertificate $dtsSatCertificate
 * @property CfdAddress[] $cfdAddresses
 * @property CfdAttribute[] $cfdAttributes
 * @property CfdDiscount[] $cfdDiscounts
 * @property CfdItem[] $cfdItems
 * @property CfdNote[] $cfdNotes
 * @property CfdTax[] $cfdTaxes
 * @property CfdTaxRegime[] $cfdTaxRegimes
 * @property CustomsPermit[] $customsPermits
 */
abstract class BaseCfd extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Cfd';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Cfd|Cfds', $n);
	}

	public static function representingColumn() {
		return 'version';
	}

	public function rules() {
		return array(
			array('version, CfdStatus_id', 'required'),
			array('folio, Currency_id, sourceFolio, approvalNbr, approvalYear, vendorParty_id, customerParty_id, SatCertificate_id, dtsSatCertificate_id, CfdStatus_id, PaymentTerm_id', 'numerical', 'integerOnly'=>true),
			array('version, voucherType, dtsVersion, dtsSatCertNbr', 'length', 'max'=>45),
			array('serial, sourceSerial', 'length', 'max'=>25),
			array('uuid', 'length', 'max'=>36),
			array('exchangeRate, sourceAmt', 'length', 'max'=>64),
			array('md5', 'length', 'max'=>32),
			array('invoice, dttm, seal, paymentType, paymentTerm, currency, paymentMethod, expeditionPlace, paymentAcctNbr, sourceDttm, dtsDttm, dtsSatSeal, dtsOriginalString, creationDt, updateDt, originalString, cbb, errorMsg, addenda', 'safe'),
			array('invoice, serial, folio, uuid, dttm, seal, paymentType, paymentTerm, exchangeRate, currency, Currency_id, voucherType, paymentMethod, expeditionPlace, paymentAcctNbr, sourceFolio, sourceSerial, sourceDttm, sourceAmt, dtsVersion, dtsDttm, dtsSatCertNbr, dtsSatSeal, dtsOriginalString, approvalNbr, approvalYear, md5, creationDt, updateDt, vendorParty_id, customerParty_id, originalString, cbb, SatCertificate_id, dtsSatCertificate_id, errorMsg, PaymentTerm_id, addenda', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, invoice, version, serial, folio, uuid, dttm, seal, paymentType, paymentTerm, exchangeRate, currency, Currency_id, voucherType, paymentMethod, expeditionPlace, paymentAcctNbr, sourceFolio, sourceSerial, sourceDttm, sourceAmt, dtsVersion, dtsDttm, dtsSatCertNbr, dtsSatSeal, dtsOriginalString, approvalNbr, approvalYear, md5, creationDt, updateDt, vendorParty_id, customerParty_id, originalString, cbb, SatCertificate_id, dtsSatCertificate_id, CfdStatus_id, errorMsg, PaymentTerm_id, addenda', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cfdStatus' => array(self::BELONGS_TO, 'CfdStatus', 'CfdStatus_id'),
			'currency0' => array(self::BELONGS_TO, 'Currency', 'Currency_id'),
			'vendorParty' => array(self::BELONGS_TO, 'Party', 'vendorParty_id'),
			'customerParty' => array(self::BELONGS_TO, 'Party', 'customerParty_id'),
			'paymentTerm0' => array(self::BELONGS_TO, 'PaymentTerm', 'PaymentTerm_id'),
			'satCertificate' => array(self::BELONGS_TO, 'SatCertificate', 'SatCertificate_id'),
			'dtsSatCertificate' => array(self::BELONGS_TO, 'SatCertificate', 'dtsSatCertificate_id'),
			'cfdAddresses' => array(self::HAS_MANY, 'CfdAddress', 'Cfd_id'),
			'cfdAttributes' => array(self::HAS_MANY, 'CfdAttribute', 'Cfd_id'),
			'cfdDiscounts' => array(self::HAS_MANY, 'CfdDiscount', 'Cfd_id'),
			'cfdItems' => array(self::HAS_MANY, 'CfdItem', 'Cfd_id'),
			'cfdNotes' => array(self::HAS_MANY, 'CfdNote', 'Cfd_id'),
			'cfdTaxes' => array(self::HAS_MANY, 'CfdTax', 'Cfd_id'),
			'cfdTaxRegimes' => array(self::HAS_MANY, 'CfdTaxRegime', 'Cfd_id'),
			'customsPermits' => array(self::MANY_MANY, 'CustomsPermit', 'Cfd_has_CustomsPermit(Cfd_id, CustomsPermit_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'customsPermits' => 'CfdHasCustomsPermit',
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'invoice' => yii::t('app', 'Invoice'),
                			'version' => yii::t('app', 'Version'),
                			'serial' => yii::t('app', 'Serial'),
                			'folio' => yii::t('app', 'Folio'),
                			'uuid' => yii::t('app', 'Uuid'),
                			'dttm' => yii::t('app', 'Dttm'),
                			'seal' => yii::t('app', 'Seal'),
                			'paymentType' => yii::t('app', 'Payment Type'),
                			'paymentTerm' => yii::t('app', 'Payment Term'),
                			'exchangeRate' => yii::t('app', 'Exchange Rate'),
                			'currency' => yii::t('app', 'Currency'),
                        			                        'Currency_id' => yii::t('app', 'Currency'),
                			'voucherType' => yii::t('app', 'Voucher Type'),
                			'paymentMethod' => yii::t('app', 'Payment Method'),
                			'expeditionPlace' => yii::t('app', 'Expedition Place'),
                			'paymentAcctNbr' => yii::t('app', 'Payment Acct Nbr'),
                			'sourceFolio' => yii::t('app', 'Source Folio'),
                			'sourceSerial' => yii::t('app', 'Source Serial'),
                			'sourceDttm' => yii::t('app', 'Source Dttm'),
                			'sourceAmt' => yii::t('app', 'Source Amt'),
                			'dtsVersion' => yii::t('app', 'Dts Version'),
                			'dtsDttm' => yii::t('app', 'Dts Dttm'),
                			'dtsSatCertNbr' => yii::t('app', 'Dts Sat Cert Nbr'),
                			'dtsSatSeal' => yii::t('app', 'Dts Sat Seal'),
                			'dtsOriginalString' => yii::t('app', 'Dts Original String'),
                			'approvalNbr' => yii::t('app', 'Approval Nbr'),
                			'approvalYear' => yii::t('app', 'Approval Year'),
                			'md5' => yii::t('app', 'Md5'),
                			'creationDt' => yii::t('app', 'Creation Dt'),
                			'updateDt' => yii::t('app', 'Update Dt'),
                        			                        'vendorParty_id' => yii::t('app', 'Vendor Party'),
                        			                        'customerParty_id' => yii::t('app', 'Customer Party'),
                			'originalString' => yii::t('app', 'Original String'),
                			'cbb' => yii::t('app', 'Cbb'),
                        			                        'SatCertificate_id' => yii::t('app', 'Sat Certificate'),
                        			                        'dtsSatCertificate_id' => yii::t('app', 'Dts Sat Certificate'),
                        			                        'CfdStatus_id' => yii::t('app', 'Cfd Status'),
                			'errorMsg' => yii::t('app', 'Error Msg'),
                        			                        'PaymentTerm_id' => yii::t('app', 'Payment Term'),
                			'addenda' => yii::t('app', 'Addenda'),
                        			                        'cfdStatus' => yii::t('app', 'Cfd Status'),
                        			                        'currency0' => yii::t('app', 'Currency0'),
                        			                        'vendorParty' => yii::t('app', 'Vendor Party'),
                        			                        'customerParty' => yii::t('app', 'Customer Party'),
                        			                        'paymentTerm0' => yii::t('app', 'Payment Term0'),
                        			                        'satCertificate' => yii::t('app', 'Sat Certificate'),
                        			                        'dtsSatCertificate' => yii::t('app', 'Dts Sat Certificate'),
                        			                        'cfdAddresses' => yii::t('app', 'Cfd Addresses'),
                        			                        'cfdAttributes' => yii::t('app', 'Cfd Attributes'),
                        			                        'cfdDiscounts' => yii::t('app', 'Cfd Discounts'),
                        			                        'cfdItems' => yii::t('app', 'Cfd Items'),
                        			                        'cfdNotes' => yii::t('app', 'Cfd Notes'),
                        			                        'cfdTaxes' => yii::t('app', 'Cfd Taxes'),
                        			                        'cfdTaxRegimes' => yii::t('app', 'Cfd Tax Regimes'),
                        			                        'customsPermits' => yii::t('app', 'Customs Permits'),
		);
	}


	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('invoice', $this->invoice, true);
		$criteria->compare('version', $this->version, true);
		$criteria->compare('serial', $this->serial, true);
		$criteria->compare('folio', $this->folio);
		$criteria->compare('uuid', $this->uuid, true);
		$criteria->compare('dttm', $this->dttm, true);
		$criteria->compare('seal', $this->seal, true);
		$criteria->compare('paymentType', $this->paymentType, true);
		$criteria->compare('paymentTerm', $this->paymentTerm, true);
		$criteria->compare('exchangeRate', $this->exchangeRate, true);
		$criteria->compare('currency', $this->currency, true);
		$criteria->compare('Currency_id', $this->Currency_id);
		$criteria->compare('voucherType', $this->voucherType, true);
		$criteria->compare('paymentMethod', $this->paymentMethod, true);
		$criteria->compare('expeditionPlace', $this->expeditionPlace, true);
		$criteria->compare('paymentAcctNbr', $this->paymentAcctNbr, true);
		$criteria->compare('sourceFolio', $this->sourceFolio);
		$criteria->compare('sourceSerial', $this->sourceSerial, true);
		$criteria->compare('sourceDttm', $this->sourceDttm, true);
		$criteria->compare('sourceAmt', $this->sourceAmt, true);
		$criteria->compare('dtsVersion', $this->dtsVersion, true);
		$criteria->compare('dtsDttm', $this->dtsDttm, true);
		$criteria->compare('dtsSatCertNbr', $this->dtsSatCertNbr, true);
		$criteria->compare('dtsSatSeal', $this->dtsSatSeal, true);
		$criteria->compare('dtsOriginalString', $this->dtsOriginalString, true);
		$criteria->compare('approvalNbr', $this->approvalNbr);
		$criteria->compare('approvalYear', $this->approvalYear);
		$criteria->compare('md5', $this->md5, true);
		$criteria->compare('creationDt', $this->creationDt, true);
		$criteria->compare('updateDt', $this->updateDt, true);
		$criteria->compare('vendorParty_id', $this->vendorParty_id);
		$criteria->compare('customerParty_id', $this->customerParty_id);
		$criteria->compare('originalString', $this->originalString, true);
		$criteria->compare('cbb', $this->cbb, true);
		$criteria->compare('SatCertificate_id', $this->SatCertificate_id);
		$criteria->compare('dtsSatCertificate_id', $this->dtsSatCertificate_id);
		$criteria->compare('CfdStatus_id', $this->CfdStatus_id);
		$criteria->compare('errorMsg', $this->errorMsg, true);
		$criteria->compare('PaymentTerm_id', $this->PaymentTerm_id);
		$criteria->compare('addenda', $this->addenda, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}