<?php

/**
 * This is the model base class for the table "SatStamp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SatStamp".
 *
 * Columns in table "SatStamp" available as properties of the model,
 * followed by relations of table "SatStamp" available as properties of the model.
 *
 * @property integer $id
 * @property integer $Cfd_id
 * @property string $uuid
 * @property string $version
 * @property string $dttm
 * @property string $certificate
 * @property string $stamp
 * @property string $originalString
 *
 * @property Cfd $cfd
 */
abstract class BaseSatStamp extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'SatStamp';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Sat Stamp|Sat Stamps', $n);
	}

	public static function representingColumn() {
		return 'uuid';
	}

	public function relations() {
		$relations = array(
			'cfd' => array(self::BELONGS_TO, 'Cfd', 'Cfd_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('Cfd_id', 'required'),
			array('Cfd_id', 'numerical', 'integerOnly'=>true),
			array('uuid, version, dttm, certificate', 'length', 'max'=>45),
			array('stamp, originalString', 'safe'),
			array('uuid, version, dttm, certificate, stamp, originalString', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Cfd_id, uuid, version, dttm, certificate, stamp, originalString', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Cfd_id', $this->Cfd_id);
		$criteria->compare('uuid', $this->uuid, true);
		$criteria->compare('version', $this->version, true);
		$criteria->compare('dttm', $this->dttm, true);
		$criteria->compare('certificate', $this->certificate, true);
		$criteria->compare('stamp', $this->stamp, true);
		$criteria->compare('originalString', $this->originalString, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                        			                        'Cfd_id' => yii::t('app', 'Cfd'),
                			'uuid' => yii::t('app', 'Uuid'),
                			'version' => yii::t('app', 'Version'),
                			'dttm' => yii::t('app', 'Dttm'),
                			'certificate' => yii::t('app', 'Certificate'),
                			'stamp' => yii::t('app', 'Stamp'),
                			'originalString' => yii::t('app', 'Original String'),
                        			                        'cfd' => yii::t('app', 'Cfd'),
		);
	}
}