<?php

/**
 * This is the model base class for the table "AutomobileMaker".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AutomobileMaker".
 *
 * Columns in table "AutomobileMaker" available as properties of the model,
 * followed by relations of table "AutomobileMaker" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Automobile[] $automobiles
 * @property AutomobileModel[] $automobileModels
 * @property AutomobileTrim[] $automobileTrims
 * @property AutomobileTrimColor[] $automobileTrimColors
 */
abstract class BaseAutomobileMaker extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'AutomobileMaker';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Automobile Maker|Automobile Makers', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'automobiles' => array(self::HAS_MANY, 'Automobile', 'AutomobileMaker_id'),
			'automobileModels' => array(self::HAS_MANY, 'AutomobileModel', 'AutomobileMaker_id'),
			'automobileTrims' => array(self::HAS_MANY, 'AutomobileTrim', 'AutomobileMaker_id'),
			'automobileTrimColors' => array(self::HAS_MANY, 'AutomobileTrimColor', 'AutomobileMaker_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                        			                        'automobiles' => yii::t('app', 'Automobiles'),
                        			                        'automobileModels' => yii::t('app', 'Automobile Models'),
                        			                        'automobileTrims' => yii::t('app', 'Automobile Trims'),
                        			                        'automobileTrimColors' => yii::t('app', 'Automobile Trim Colors'),
		);
	}
    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BaseAutomobileMaker::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}