<?php

/**
 * This is the model base class for the table "AutomobileModel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AutomobileModel".
 *
 * Columns in table "AutomobileModel" available as properties of the model,
 * followed by relations of table "AutomobileModel" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $AutomobileMaker_id
 *
 * @property AutomobileMaker $automobileMaker
 * @property AutomobileTrim[] $automobileTrims
 */
abstract class BaseAutomobileModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'AutomobileModel';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Automobile Model|Automobile Models', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, AutomobileMaker_id', 'required'),
			array('AutomobileMaker_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('id, name, AutomobileMaker_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'automobileMaker' => array(self::BELONGS_TO, 'AutomobileMaker', 'AutomobileMaker_id'),
			'automobileTrims' => array(self::HAS_MANY, 'AutomobileTrim', 'AutomobileModel_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'name' => yii::t('app', 'Name'),
                        			                        'AutomobileMaker_id' => yii::t('app', 'Automobile Maker'),
                        			                        'automobileMaker' => yii::t('app', 'Automobile Maker'),
                        			                        'automobileTrims' => yii::t('app', 'Automobile Trims'),
		);
	}

    public function defaultScope() {
        return array('order' => $this->getTableAlias(false, false) . '.' . BaseAutomobileModel::representingColumn() . ' ASC');
    }

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('AutomobileMaker_id', $this->AutomobileMaker_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}
}