<?php

/**
 * This is the model base class for the table "MasterAccount".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MasterAccount".
 *
 * Columns in table "MasterAccount" available as properties of the model,
 * followed by relations of table "MasterAccount" available as properties of the model.
 *
 * @property integer $id
 * @property string $alias
 * @property string $name
 *
 * @property MasterAccountAttribute[] $masterAccountAttributes
 */
abstract class BaseMasterAccount extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'MasterAccount';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Master Account|Master Accounts', $n);
	}

	public static function representingColumn() {
		return 'alias';
	}

	public function rules() {
		return array(
			array('alias, name', 'required'),
			array('alias', 'length', 'max'=>45),
			array('id, alias, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'masterAccountAttributes' => array(self::HAS_MANY, 'MasterAccountAttribute', 'MasterAccount_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'alias' => yii::t('app', 'Alias'),
                			'name' => yii::t('app', 'Name'),
                        			                        'masterAccountAttributes' => yii::t('app', 'Master Account Attributes'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}