<?php

/**
 * This is the model base class for the table "Role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Role".
 *
 * Columns in table "Role" available as properties of the model,
 * followed by relations of table "Role" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $class
 *
 * @property PartyRole[] $partyRoles
 */
abstract class BaseRole extends EAVActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Role';
	}

	public static function label($n = 1) {
        return Yii::t('app', 'Role|Roles', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function relations() {
		$relations = array(
			'partyRoles' => array(self::HAS_MANY, 'PartyRole', 'Role_id'),
		);
                return array_merge($relations, parent::relations());
	}
	public function rules() {
		return array(
			array('code, name, class', 'length', 'max'=>45),
			array('code, name, class', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, class', 'safe', 'on'=>'search'),
		);
	}
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('class', $this->class, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination' => array('pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize'])),
		));
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                			'id' => yii::t('app', 'Id'),
                			'code' => yii::t('app', 'Code'),
                			'name' => yii::t('app', 'Name'),
                			'class' => yii::t('app', 'Class'),
                        			                        'partyRoles' => yii::t('app', 'Party Roles'),
		);
	}
}